name: Deployment Prep
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: read-all

jobs:
  config:
    if: github.repository == 'ermradulsharma/github-readme-stats'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Deployment Prep
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
