name: Deployment Prep
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: read-all

jobs:
  config:
    if: github.repository == 'ermradulsharma/github-readme-stats'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2 # v6.0.2
      - name: Deployment Prep
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@v7.1.0 # v7.1.0
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
