name: "Pull Request Labeler"
on:
  - pull_request_target

permissions: read-all

jobs:
  triage:
    if: github.repository == 'ermradulsharma/github-readme-stats'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
